# Generated by Django 3.0.8 on 2022-07-08 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoPlanesServiciosEspeciales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlanesServiciosEspeciales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isla_N.GrupoPlanesServiciosEspeciales')),
            ],
        ),
    ]
